language: node_js
node_js:
- 8.9.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libasound2-dev
env:
- CXX=g++-4.8
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    rooms:
      secure: qFxz3LjwPA+DU8B24uyzqaHy1fcJVGuHN/djdTN9Tz9jQv2Vr7BAV26bXkHy7og3JD0JhD94p4z0TH/abwCEpHFR8+UNwIQxscZipZEhmMyGdVS9BdtbatPAvQkYbxqGjxekVK+pyyKXrbqb+co5bX6q6/ThXccPrmpnvREQ3j+Tif2SlAlfj1u2mLJsCC+TvyzWcB7iJ3PSTio24YTFyu2Sb89jlZgh9UBIL82pteUMnxEbe0+Cn1Ixw5OhTBKDhvvxO53D0KODPcQZqoLmEs32hSIdzM2dr6nIMkzMqVDoCVNOauo4oP/3TSKa6Tv6q5PUcAOvD+ES9BDYxeKxarTmLn4cnGL/a4pbNVTpAYdYI1w7tGTZTO0uRnqzZ6sgfcsMg+ATX1tlBwwZU4stFBTOPHJGeGSmcfVAwZuMzdbFa23pbXqrMspYfTZGhw838lH7gj6Ws3qycxc4WiC7N2cGCMiusGnQjp7XEpQtK+fV0zKvm3kjWzeBwRH+YW5IhxQyeH76uC56Ty/bXy/La8L0hBLiKG+gcn8jQ96Elo98PcDhwLifaB7uH0oFgPlv2HTW/s+98KsWOp1qJbhFlwFPaRr5Ayl2TxBe9/qU1UHtUs43G0qQ3bzwsa472ASPRIq4ouFBVcuzpUpZZOMiu9o6253A68/lGo19M23STfs=
    on_success: change
    on_pull_requests: false
before_script:
- npm prune
after_success:
- npm run coveralls
- npm run semantic-release
